### ISSUE TITLE
fatal error LNK1181: cannot open input file 'j2pkcs11.lib'

### ISSUE THREAD

**Issue by johannkropf** [gluonhq/client-maven-plugin#205] opened 2020-07-02 06:56 UTC
Hello, if I run mvn client:build I get the error LNK1181. In the process-link logfile I see that there is a missing /LIBPATH entry to the directory %GRAALVM_HOME%\lib\static\windows-amd64 where the file j2pkcs11.lib resides.

If I copy this file in another libpath it works for this file, but the next file is reported as missing (java.lib).

I am using the client plugin 0.1.27, GraalVM CE 20.2.0-dev (build 11.0.7+10-jvmci-20.2-b01) and VS 2019 Version 19.25.28614 für x64.

Thank you for your help!

**Comment by tiainen** [comment] 2020-07-02 13:22
Duplicate of https://github.com/gluonhq/client-maven-plugin/issues/203

**Closed by tiainen** 2020-07-02 13:22 UTC
