### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/client-maven-plugin#223] opened 2020-08-11 05:38 UTC
I see this similar issue at https://github.com/gluonhq/client-maven-plugin/issues/38, I am still getting the similar error:

```
Process
=======
link

Command Line
============
clang /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/hellogluon/AppDelegate.o /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/tmp/SVM-1597123267434/com.gluonhq.hello.hellogluon.o /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/tmp/SVM-1597123267434/llvm/llvm.o -ljava -lnio -lzip -lnet -lprefs -ljvm -lfdlibm -lz -ldl -lj2pkcs11 -lsunec -ljaas -lextnet -lstdc++ -w -fPIC -arch arm64 -mios-version-min=11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -Wl,-force_load,/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/libprism_es2.a -Wl,-force_load,/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/libglass.a -Wl,-force_load,/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/libjavafx_font.a -Wl,-force_load,/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/libprism_common.a -Wl,-force_load,/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/libjavafx_iio.a -lpthread -llibchelper -lffi -ldarwin -Wl,-framework,Foundation -Wl,-framework,UIKit -Wl,-framework,CoreGraphics -Wl,-framework,MobileCoreServices -Wl,-framework,OpenGLES -Wl,-framework,CoreText -Wl,-framework,QuartzCore -Wl,-framework,ImageIO -Wl,-framework,CoreBluetooth -Wl,-framework,CoreImage -Wl,-framework,CoreLocation -Wl,-framework,CoreMedia -Wl,-framework,CoreMotion -Wl,-framework,CoreVideo -Wl,-framework,Accelerate -Wl,-framework,AVFoundation -Wl,-framework,AudioToolbox -Wl,-framework,MediaPlayer -Wl,-framework,UserNotifications -Wl,-framework,ARKit -Wl,-framework,AVKit -Wl,-framework,SceneKit -Wl,-framework,StoreKit -o /Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/hellogluon.app/hellogluon -L/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib -L/Users/incomemac/Downloads/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/svm/clibraries/ios-arm64 -L/Users/incomemac/.gluon/substrate/javaStaticSdk/11-ea+0/ios-arm64/labs-staticjdk/lib/static -L/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib -Wl,-force_load,/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib/libLifecycle.a -Wl,-force_load,/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib/libStatusbar.a -Wl,-force_load,/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib/libDisplay.a -Wl,-force_load,/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib/libUtil.a -Wl,-force_load,/Users/incomemac/Desktop/income-workplace/HelloGluon/target/client/arm64-ios/gvm/lib/libStorage.a

Output
======
Undefined symbols for architecture arm64:
  "___svm_vm_is_static_binary", referenced from:
      _JVM_FindLibraryEntry in libjvm.a(JvmFuncs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Result
======
result: 1
```

I am using GraalVM CE 20.2.0-dev-20200807_1145 version, and using the Java come with the same downloaded GraalVM:

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0-dev (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0-dev (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

``` 

I can run using maven `javafx:run`, and successfully build with `client:compile`, but fail with `client:link`.

Below is my full pom.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.gluonhq.hello</groupId>
	<artifactId>hellogluon</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>hellogluon</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>11</maven.compiler.release>
		<javafx.version>14.0.1</javafx.version>
		<attach.version>4.0.8</attach.version>
		<client.plugin.version>0.1.29</client.plugin.version>
		<mainClassName>com.gluonhq.hello.HelloGluon</mainClassName>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq</groupId>
			<artifactId>charm-glisten</artifactId>
			<version>6.0.5</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>display</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>lifecycle</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>statusbar</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>storage</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>util</artifactId>
			<version>${attach.version}</version>
		</dependency>

		<dependency>
			<groupId>com.gluonhq</groupId>
			<artifactId>charm</artifactId>
			<version>5.0.2</version>
		</dependency>

		<dependency>
			<groupId>my.testing</groupId>
			<artifactId>my.testing</artifactId>
			<version>0.0.1</version>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.3</version>
		</dependency>

		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>itextpdf</artifactId>
			<version>5.5.7</version>
		</dependency>

		<dependency>
			<groupId>com.itextpdf.tool</groupId>
			<artifactId>xmlworker</artifactId>
			<version>5.5.7</version>
		</dependency>

		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker-gae</artifactId>
			<version>2.3.23</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.5</version>
		</dependency>

		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>2.3.2</version>
		</dependency>

		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk15on</artifactId>
			<version>1.50</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk15on</artifactId>
			<version>1.50</version>
		</dependency>
		<dependency>
			<groupId>org.python</groupId>
			<artifactId>jython</artifactId>
			<version>2.7.0</version>
		</dependency>

	</dependencies>

	<repositories>
		<repository>
			<id>Gluon</id>
			<url>https://nexus.gluonhq.com/nexus/content/repositories/releases</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>

			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.4</version>
				<configuration>
					<mainClass>${mainClassName}</mainClass>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.gluonhq</groupId>
				<artifactId>client-maven-plugin</artifactId>
				<version>${client.plugin.version}</version>
				<configuration>
					<!-- Uncomment to run on iOS or Android: -->
					<target>ios</target>
					<!-- <target>android</target> -->
					<attachList>
						<list>display</list>
						<list>lifecycle</list>
						<list>statusbar</list>
						<list>storage</list>
					</attachList>
					<mainClass>${mainClassName}</mainClass>
					<nativeImageArgs>--allow-incomplete-classpath</nativeImageArgs>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-install-plugin</artifactId>
				<version>2.5.2</version>
				<executions>
					<execution>
						<phase>initialize</phase>
						<goals>
							<goal>install-file</goal>
						</goals>
						<configuration>
							<file>lib/pdfprint.jar</file>
							<groupId>my.testing</groupId>
							<artifactId>my.testing</artifactId>
							<version>0.0.1</version>
							<packaging>jar</packaging>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

Anyone can help to advise?

**Comment by tiainen** [comment] 2020-08-11 07:25
This is a duplicate of https://github.com/gluonhq/substrate/issues/737

It will be included in the next version (0.1.30) of the client maven plugin.

**Closed by tiainen** 2020-08-11 07:25 UTC

**Comment by mipastgt** [comment] 2020-08-11 07:31
You mean 0.1.31, right? 0.1.30 has been available already for som time.

**Comment by tiainen** [comment] 2020-08-11 08:18
You are correct, I meant `0.1.31`.

**Comment by jperedadnr** [comment] 2020-08-11 08:47
@samyc1201 In the meantime, you can use the 0.1.31-SNAPSHOT version of the Client plugin, by adding this to the pom:

```
<pluginRepositories>
    <pluginRepository>
        <id>snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

**Comment by samyc1201** [comment] 2020-08-12 05:31
> 0.1.31-SNAPSHOT

@jperedadnr 

Tried this snapshot, the error message change to a different one:

```
[Wed Aug 12 13:26:49 SGT 2020][INFO] ==================== LINK TASK ====================
[Wed Aug 12 13:26:51 SGT 2020][INFO] [SUB] Undefined symbols for architecture arm64:
[Wed Aug 12 13:26:51 SGT 2020][INFO] [SUB]   "___isPlatformVersionAtLeast", referenced from:
[Wed Aug 12 13:26:51 SGT 2020][INFO] [SUB]       _Java_com_gluonhq_attach_statusbar_impl_IOSStatusBarService_setNativeColor in libStatusbar.a(Statusbar.o)
[Wed Aug 12 13:26:52 SGT 2020][INFO] [SUB] ld: symbol(s) not found for architecture arm64
[Wed Aug 12 13:26:52 SGT 2020][INFO] [SUB] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[Wed Aug 12 13:26:52 SGT 2020][SEVERE] Process link failed with result: 1
```

**Comment by jperedadnr** [comment] 2020-08-12 08:42
@samyc1201 That's a different issue. It is related to Gluon Attach. There was a change in 4.0.8 in the StatusBar service, that requires Xcode 11, so it seems your Xcode is a little bit old. You can upgrade it, or alternatively keep the statusBar service with a lower version (4.0.7).
