### ISSUE TITLE
How to add program arguments to native-iamge like "-port=10800"

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/client-maven-plugin#244] opened 2020-08-24 07:30 UTC
`public class Hello {
    public static void main(String[] args) {
        System.out.println(args);
    }
}`

**Comment by jperedadnr** [comment] 2020-08-24 08:11
On desktop you can run your native image with the arguments:
`./myapp -port=10800`

Duplicate of https://github.com/gluonhq/client-maven-plugin/issues/120

**Closed by jperedadnr** 2020-08-24 08:11 UTC
